name: Deploy VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Subir p VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /var/www/solarklin-cora/klinlabs-cora-proxy &&
            echo 'Enviando codigo...' &&
            git pull &&
            echo 'Instalando dependencias...' &&
            npm install --production &&
            echo 'Buildando..' &&
            npm run build &&
            echo 'Reiniciando PM2...' &&
            pm2 restart cora-api
          "